POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndoYWNreV90b2JhY2NpIiwiaWQiOiI2MTQwNzhhNzQzODAxOTBkZDAzMThiNmMiLCJpYXQiOjE2MzE2MTUxNzV9.JFr8EB1kbe46-hXNysMdcIJTq8OgxqXLScD5uZhVsy4

{
  "title": "Refactoring CSS: Strategy, Regression Testing And Maintenance (Part 2)",
  "author": "Adrian Bece",
  "url": "https://www.smashingmagazine.com/2021/08/refactoring-css-strategy-regression-testing-maintenance-part2/",
  "likes": 0,
  "comments": []
}