PUT http://localhost:3003/api/blogs/6117b6eed085fb1914dc3b54
Content-Type: application/json

{
  "user": "6117b6edd085fb1914dc3b45",
  "likes": -15,
  "author": "Adrian Bece",
  "title": "Refactoring CSS: Strategy, Regression Testing And Maintenance (Part 2)",
  "url": "https://www.smashingmagazine.com/2021/08/refactoring-css-strategy-regression-testing-maintenance-part2/"
}